mod error;
#[cfg(feature = "capture")] pub mod capture;
#[cfg(feature = "capture")] pub use capture::{CaptureHandle, Direction};
#[cfg(feature = "metrics-full")]
pub mod recorder;
mod io;
mod atom;
mod core;
mod destinations;

pub use io::departure::{Departure, StreamDeparture, Transload, ChannelTransload};
pub use io::destination::StreamDestination;
pub use error::{RailscaleError, ErrorKind, Phase};
pub use atom::frame::{Frame, ParsedData};
pub use atom::phase::{FramePhase, PhasedFrame, PhasedBuffer};
pub use atom::derive::{MatchAtom, DerivedEffect, DerivationFormula, DeriverSession};
pub use atom::parser::FrameParser;
pub use core::pipeline::FramePipeline;
pub use core::composed::{Composed, StreamTransform};
pub use core::service::{Pipeline, Service};
pub use io::router::DestinationRouter;
pub use io::source::StreamSource;
pub use destinations::route::{MatchStrategy, MatchingRouter};
pub use destinations::file::FileDestination;
pub use core::error_mapper::{ErrorToFrames, ErrorToBytes};
pub use core::service::BufferLimits;
pub use io::batcher::BatchWriter;
pub use tokio_util::sync::CancellationToken;
pub use atom::switch_rail::{SwitchRail, IdentityRail};
pub use core::turnout::{Turnout, SimpleTurnout, FramePipelineAdapter};
pub use core::shuttle::ShuttleLink;
pub use core::shunt::{Shunt, RouterShunt};
pub use atom::raw::{RawFrame, RawParser, RawPipeline};
pub use core::hook::{ConnectionHook, NoHook};
pub use core::stabling::{Stabling, StablingConfig};
